name = "Cobalt Core"
home = "https://discord.com/channels/731205301247803413/1190007746641272912"
default_url = "https://github.com/Isaac-SOL/CobaltCoreArchipelagoMod/releases/download/release/{{version}}/cobalt_core.apworld"

[versions]
"1.1.5" = {}
