name = "Peaks of Yore"
home = "https://discord.com/channels/731205301247803413/1332506808182378677"

[versions]
# https://discord.com/channels/731205301247803413/1332506808182378677/1474089214604873842
"1.7.2" = { local = "../apworlds/peaks_of_yore-1.7.2.apworld" }
