name = "TOEM: A Photo Adventure"
home = "https://discord.com/channels/731205301247803413/1255989734497587241"
default_url = "https://github.com/bbernardoni/Archipelago.TOEM/releases/download/{{version}}/toem.apworld"

[versions]
"1.1.1" = {}
"1.9.0" = {}
