[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_BattleBlockTheater_commanderdot', option='Secret_Levels_Enabled')"]]
__expected__ = "error"
__version__ = ">=1.2.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_BattleBlockTheater_commanderdot', option='Time_Stamp_Checks_Enabled')"]]
__expected__ = "error"
__version__ = ">=1.2.1"
